name: Run Pre-commit

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv sync
          export PATH="$PATH:$(pwd)/.venv/bin"
          .venv/bin/pip install ruff pylint pre-commit 
          .venv/bin/pre-commit run -a
