name: Run Pre-commit

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          python3 -mpip install -U uv
          uv sync
          export PATH="$PATH:$(pwd)/.venv/bin"
          .venv/bin/python3 -mpip install ruff pylint pre-commit 
          .venv/bin/pre-commit run -a
