name: Run Pre-commit

on: [push, pull_request]

jobs:
  pre_commit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - name: Install dependencies
        run: |
          pip install -U uv
          uv sync
          export PATH="$PATH:$(pwd)/.venv/bin"
          uv add pre-commit ruff pylint
          .venv/bin/pre-commit run -a
